-- Sample data for Job & Networking Portal

-- Insert sample users (these will be created when users sign up)
-- Note: Real user IDs will be generated by Supabase Auth

-- Insert sample jobs
INSERT INTO public.jobs (title, description, company, location, job_type, salary_min, salary_max, skills_required, posted_by, status) VALUES
('Senior Frontend Developer', 'We are looking for an experienced React developer to join our team. You will be responsible for building user-facing features and ensuring great user experience.', 'TechCorp Inc', 'San Francisco, CA', 'full-time', 120000, 160000, ARRAY['React', 'TypeScript', 'Next.js', 'Tailwind CSS'], (SELECT id FROM auth.users LIMIT 1), 'active'),
('Blockchain Developer', 'Join our Web3 team to build the future of decentralized applications. Experience with Solidity and Ethereum required.', 'CryptoStartup', 'Remote', 'contract', 80, 120, ARRAY['Solidity', 'Web3.js', 'Ethereum', 'Smart Contracts'], (SELECT id FROM auth.users LIMIT 1), 'active'),
('UI/UX Designer', 'Create beautiful and intuitive user interfaces for our mobile and web applications. Portfolio required.', 'DesignStudio', 'New York, NY', 'full-time', 90000, 130000, ARRAY['Figma', 'Adobe Creative Suite', 'User Research', 'Prototyping'], (SELECT id FROM auth.users LIMIT 1), 'active'),
('Data Scientist', 'Analyze large datasets and build machine learning models to drive business insights and product improvements.', 'DataCorp', 'Austin, TX', 'full-time', 110000, 150000, ARRAY['Python', 'Machine Learning', 'SQL', 'TensorFlow'], (SELECT id FROM auth.users LIMIT 1), 'active'),
('DevOps Engineer', 'Manage our cloud infrastructure and CI/CD pipelines. Experience with AWS and Kubernetes preferred.', 'CloudTech', 'Seattle, WA', 'full-time', 130000, 170000, ARRAY['AWS', 'Kubernetes', 'Docker', 'Terraform'], (SELECT id FROM auth.users LIMIT 1), 'active');

-- Insert sample posts
INSERT INTO public.posts (author_id, content, post_type) VALUES
((SELECT id FROM auth.users LIMIT 1), 'Just launched my new portfolio website! Check it out and let me know what you think. Built with Next.js and deployed on Vercel.', 'update'),
((SELECT id FROM auth.users LIMIT 1), 'What are the best practices for Web3 security? Looking for advice on smart contract auditing.', 'question'),
((SELECT id FROM auth.users LIMIT 1), 'Pro tip: Always test your responsive design on real devices, not just browser dev tools. The difference can be significant!', 'advice');

-- Seed data is already complete and ready to execute
